export const COMBAT_CONFIG = {
  MIN_AIM_ANGLE_DEG: -80,
  MAX_AIM_ANGLE_DEG: 80,
  AIM_STEP_DEG: 2,

  MIN_POWER: 4,
  MAX_POWER: 25,      // raised from 14
  POWER_STEP: 0.3,    // slightly faster adjustment
  DEFAULT_POWER: 10,

  PROJECTILE_RADIUS: 6,
  PROJECTILE_DENSITY: 1,
  PROJECTILE_RESTITUTION: 0.2,
  PROJECTILE_FRICTION: 0.4,

  EXPLOSION_RADIUS: 70,
  EXPLOSION_FORCE: 9,
  EXPLOSION_DAMAGE: 35,

  SHOT_COOLDOWN_MS: 400,
} as const