export const WEAPON_TYPES = {
  BAZOOKA: 'bazooka',
  GRENADE: 'grenade',
  MISSILE: 'missile',
  CLUSTER_BOMB: 'cluster_bomb',
  PISTOL: 'pistol',
  LASER: 'laser',
  FLAME_THROWER: 'flame_thrower',
} as const

export const WEAPON_CONFIG = {
  [WEAPON_TYPES.BAZOOKA]: {
    name: 'Bazooka',
    projectileSpeed: 1.0,
    damage: 35,
    explosionRadius: 70,
    projectileColor: 0xffcc33,
    projectileSize: 6,
    ammo: -1, // Infinito
    description: 'Explosión estándar confiable',
    explosionType: 'fire',
    hasTrail: true,
    trailColor: 0xff6600,
  },
  [WEAPON_TYPES.GRENADE]: {
    name: 'Granada',
    projectileSpeed: 0.8,
    damage: 40,
    explosionRadius: 80,
    projectileColor: 0x44aa44,
    projectileSize: 5,
    ammo: 5,
    description: 'Rebota y explota con timer de 5s',
    bounces: 3,
    fuseTime: 5000, // Cambiado a 5 segundos
    explosionType: 'normal',
    hasTimer: true,
    showCountdown: true, // Nueva propiedad para mostrar contador
  },
  [WEAPON_TYPES.MISSILE]: {
    name: 'Misil Teledirigido',
    projectileSpeed: 0.6,
    damage: 50,
    explosionRadius: 90,
    projectileColor: 0xff4444,
    projectileSize: 8,
    ammo: 3,
    description: 'Apunta con mouse y busca el objetivo',
    guidanceForce: 2.0,
    explosionType: 'fire',
    hasTrail: true,
    trailColor: 0xff0000,
    isGuided: true,
    requiresTarget: true,
  },
  [WEAPON_TYPES.CLUSTER_BOMB]: {
    name: 'Bomba Racimo',
    projectileSpeed: 0.7,
    damage: 25,
    explosionRadius: 50,
    projectileColor: 0xaa44ff,
    projectileSize: 7,
    ammo: 2,
    description: 'Explota en múltiples bombitas',
    clusterCount: 8,
    clusterRadius: 80,
    clusterDamage: 15,
    explosionType: 'normal',
    hasTimer: true,
    fuseTime: 2000,
  },
  [WEAPON_TYPES.PISTOL]: {
    name: 'Pistola',
    projectileSpeed: 1.8,
    damage: 20,
    explosionRadius: 0, // Sin explosión
    projectileColor: 0xcccccc,
    projectileSize: 2,
    ammo: 15,
    description: 'Rápida y precisa, sin explosión',
    hasTrail: true,
    trailColor: 0xffffff,
    directDamage: true,
  },
  [WEAPON_TYPES.LASER]: {
    name: 'Láser',
    projectileSpeed: 3.0,
    damage: 30,
    explosionRadius: 0,
    projectileColor: 0x00ffff,
    projectileSize: 1,
    ammo: 6,
    description: 'Instantáneo, atraviesa terreno',
    isInstant: true,
    penetrates: true,
    explosionType: 'electric',
    excludeShooter: true,
  },
  [WEAPON_TYPES.FLAME_THROWER]: {
    name: 'Lanzallamas',
    projectileSpeed: 0.5,
    damage: 8,
    explosionRadius: 25,
    projectileColor: 0xff6600,
    projectileSize: 4,
    ammo: 20,
    description: 'Múltiples llamas de corto alcance',
    isFlamethrower: true,
    flameCount: 3,
    flameLife: 1000,
    explosionType: 'fire',
    excludeShooter: true,
  },
} as const